version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nodejs-app:
    build: .
    container_name: nodejs_container
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: my_database
      JWT_SECRET: my_jwt_secret
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql_data:
